  server:
    port: 9093
  spring:
    application:
      name: zuulServeOrEdgeService
    cloud:
      gateway:
        routes:
          - id: micro1
            uri: http://localhost:9091
            predicates:
              - Path=/api/message
          - id: micro2
            uri: http://localhost:9092
            predicates:
              - Path=/api/read-message
    main:
      web-application-type: reactive
